### ISSUE TITLE
An error occurred while attempting to auto-merge

### ISSUE THREAD

**Issue by havenchyk** [alexwilson/enable-github-automerge-action#154]
I'm not quite sure that there is a problem with your action, the action was able to enable auto-merge, unfortunately, auto-merge feature couldn't merge my PR

![image](https://user-images.githubusercontent.com/1291032/151350483-d77f0a0e-0a96-4f4f-aa02-27da903e9e08.png)

Example of the error
![image (6)](https://user-images.githubusercontent.com/1291032/151350554-861b6d29-57ee-44a9-833f-107b7b8e1b36.png)

Do you have any idea if it could be a problem with permissions or maybe you faced such issue?

**Comment by alexwilson** [comment]
Hey @havenchyk, would you mind linking to an example PR where this has happened?

**Comment by havenchyk** [comment]
Hey @alexwilson no worries, we figured out with GitHub team that it was a bug on their side. Thanks for reply
